### ISSUE TITLE
Dish Station BPM Smudge Generation

### ISSUE THREAD

**Issue by HexagonsEnjoyer** [lawrencemsteven/BFBB#36]
Getting the dishwashing station to take the bpm from composer and generate smudges for 4/4 time

**Comment by ryondinkus** [comment]
Hey FYI, there's an open PR #35 that affects the Dish Station quite a bit. To avoid merge conflicts, would you mind checking and approving #35 real quick? Once you do, I can merge it into main, then you can rebranch off of main and work on this issue.
